0.10 fix attribute import error
DH-Center-Tuebingen/Spacialist pull request #491
Opened 2024-05-03 11:48 UTC by Severino

Fixed multiple errors with the updated importer:

- Attribute errors were not displayed correctly
- Whitespaces caused imports to fail
- Fixed a display error: On small screens the control section was not scrollable, but each of the small windows were
- Fixed that name column (and parent colum) can be selected in the _Attribute-Mapping_ but the import faills without any error. Now it will import the columns despite beeing simultaneously name or parent column.

2024-05-13 14:33 UTC, Severino commented
@v1r0x can you have a look at this?

2024-05-14 08:06 UTC, Severino commented on app/Http/Controllers/EntityController.php
>                  continue;
I think here was the name column or parent column error

2024-05-14 12:01 UTC, v1r0x reviewed
Looks good so far. I did some small adjustments

1. I excluded the `system-separator` datatype from the attribute selection list (added as new optional parameter in store getter)
2. Moved row trim function to global helper
3.1. Error message for errors during import was hardcoded in english
3.2. Error message was missing the column name (only 1-based index and datatype was shown), so I added the name to the exceptions and structs. I'm not sure if this has some side effects for any other import error. Can you please confirm there are no side effects?

2024-06-10 12:05 UTC, v1r0x requested changes
Beside the artisan command: :+1:

2024-06-10 12:05 UTC, v1r0x commented on app/Console/Commands/RefreshTesting.php
> +    })->describe('Resets the testing database and seeds the demo data.');
I'm not sure if we should "polute" the test namespace with our own commands. Maybe create our own spacialist namespace where we can also add other commands (e.g. create users from cli, ...)

2024-06-17 06:48 UTC, merged